version: '{build}'
skip_tags: true
image:
  - Visual Studio 2022
  - Ubuntu
build_script:
- ps: ./Build.ps1
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
    - sh build.sh
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
- path: artifacts/Serilog.*.snupkg
deploy:
- provider: NuGet
  api_key:
    secure: LE+O+3Zs0nz2F/+M4eDvKBhEBUpUV0t864vN/2dxwa7aIVqeU3pKSMjWRX+JWJ49
  on:
    branch: /^(main|dev)$/
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifact: /Serilog.*(\.|\.s)nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: main
