version: '{build}'
skip_tags: true
image:
  - Visual Studio 2022
  - Ubuntu
build_script:
- ps: ./Build.ps1
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
    - sh build.sh
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
- path: artifacts/Serilog.*.snupkg
deploy:
- provider: NuGet
  server: https://nuget.pkg.github.com/MonticolaExplorator/index.json
  api_key:
    secure: 87VXONffNiU8ErfeaSaETZLTOfF7GKHqv/CD0tNpYc52+kZlBP2GgsQhpOjv8Reo
  on:
    branch: /^(main|dev|symbolspck)$/
- provider: GitHub
  auth_token:
    secure: 87VXONffNiU8ErfeaSaETZLTOfF7GKHqv/CD0tNpYc52+kZlBP2GgsQhpOjv8Reo
  artifact: /Serilog.*(\.|\.s)nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: (main|symbolspck)
